[package]
name = "star"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
logos = "0.16.0"
wasm-encoder = "0.243.0"
wasmtime = { version = "29.0", optional = true }

[features]
default = ["cli"]
cli = ["wasmtime"]
